### ISSUE TITLE
Memory leak introduced some time after version 2.x

### ISSUE THREAD

**Issue by Jalle19** [contentful/contentful.php#257]
We've tried two times to upgrade the version of this SDK that we use (first from 2.x to 3.x, now from 2.x to 4.x) but both times we're run into memory leaks that have turned out to be showstoppers.

Here's what it looks like when we attempt to synchronize all assets from a Contentful space:

```
$ php artisan contentful:assets:sync --ignoreExisting -vvv
Synchronizing assets/media...
 32300/43028 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░]  75% 4 mins/6 mins 256.0 MiB

PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 122880 bytes) in /vagrant/api/vendor/guzzlehttp/psr7/src/Stream.php on line 94
```

On 2.x it used to look like this:

```
$ php artisan contentful:assets:sync --ignoreExisting -vvv
Synchronizing assets/media...
 43029/43029 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100% 3 mins/3 mins 22.0 MiB

Done, synchronized 43029 assets
```

As you can see the memory usage is supposed to remain fairly constant (it started out at 20.0 MiB).

We're using the console commands provided by this library: https://github.com/digiaonline/lumen-contentful-sync/ (tested using a WIP branch that supports the latest SDK: https://github.com/digiaonline/lumen-contentful-sync/pull/15).

Even if I strip all our own processing logic for the loop the memory leak persists, which further confirms my suspicion that the SDK is somehow at fault. Here's the gist of the loop:

```php
$this->output->progressStart($this->getClient()->getAssets($this->getTotalQuery())->getTotal());

do {
    $assets = $this->getClient()->getAssets($this->getQuery());

    // Process the current batch
    foreach ($assets as $asset) {
        // SNIP: Processing would normally happen here
        $this->numSynchronized++;

        $this->output->progressAdvance();
    }

    // Move on to the next batch
    $this->skip += $assets->getLimit();
} while ($this->skip < $assets->getTotal());

$this->output->progressFinish();
```

The full source for the command can be read here: https://github.com/digiaonline/lumen-contentful-sync/blob/71b661373d4ab152aa245b6872405ff215c3b285/src/Console/Commands/SyncAssetsCommand.php

**Comment by dborsatto** [comment]
Hey Sam,

I think I know where the issue is. To be honest, I'm surprised it took this much before this surfaced.

In version 3 and 4 of the SDK, I made a choice to use a [resource pool](https://github.com/contentful/contentful.php/blob/master/src/ResourcePool.php) (known as instance repository in version 3), which basically keeps all built entries and assets in memory. This is an optimization done with the normal use case in mind, a simple short-lived process which handles a few entries or assets at a time. This made memory leaks issues more likely, but given how much I was able to simplify certain parts of the SDK, I chose to make this choice.

Now, as this is a fundamental part of how the SDK works, I can't just scrap it to fix this issue. But I can't let this issue stay, of course, so I'd like to propose an idea to you and see if that would be acceptable.

The gist is: instead of keeping everything in PHP memory, delegate that storing part to a PSR-6 implementation. This would possibly make things a bit slower (can't say how much), but it would keep the resource pool class from being a memory hog.

Right now the resource pool class acts as a sort of wrapper around a PSR-6 cache pool, but it lazy loads and keeps things in memory. What I have in mind is being able to completely avoid keeping in memory, and it would only act as a JSON decoder/encoder between the client and the cache pool.

The tradeoffs would be 2:

* Having to manually set up a PSR-6 cache pool, though it should be pretty straightforward.
* Slightly longer times, as the resource pool would have to JSON encode on every save, and JSON decode on every fetch. Though from what I understand, in your situation this shouldn't be too much an issue.

Does this seem reasonable to you?

Cheers,

Davide

**Comment by Jalle19** [comment]
I'll see if I can work around the issue with a PSR-6 cache, we have one of those easily available in the project anyway.

Instead of having the ResourcePool keep things in memory, wouldn't it be better to use an array-based (i.e. in-memory) PSR-6 implementation by default instead?

**Comment by Jalle19** [comment]
@dborsatto any chance you could make the various properties in `Client` protected instead of private? This way we could override the Client and configure a custom ResourcePool that does nothing (basically like VoidCacheAdapter)? Alternatively the client could have setter methods for these private properties, i.e. `setResourcePool(ResourcePoolInterface $resourcePool)`

**Comment by Jalle19** [comment]
@dborsatto I tried using a Redis-backed PSR-6 cache item pool, but the memory usage still ran amok.

**Comment by dborsatto** [comment]
Yes, because in order to allow this, I need first to add a resource pool which works as a passthough only. I'm working on it, hopefully I'll release something by the end of the day.

Allowing to overriding the resource pool once the client is built is not actually a good idea, because the resource builder is also involved. So even though they are decoupled from each other, there should be a guarantee that the resource builder and the client rely on the same resource pool. For this reason I'm working on adding an option to use a low-memory resource pool using the `ClientOptions` object, so it will be built on the client constructor and it will guarantee integrity.

**Comment by Jalle19** [comment]
@dborsatto I tried adding a `return false;` to `ResourcePool::save()` and the memory leak is still there, so maybe we're looking in the wrong place after all?

**Comment by Jalle19** [comment]
In fact that made it even worse:

```
$ php artisan contentful:assets:sync --ignoreExisting -vvv
Synchronizing assets/media...
  5600/43059 [▓▓▓░░░░░░░░░░░░░░░░░░░░░░░░░]  13%  1 min/9 mins 252.2 MiB

PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in /vagrant/api/vendor/guzzlehttp/psr7/src/MessageTrait.php on line 181
```

**Comment by dborsatto** [comment]
The return value of `ResourcePool::save()` is there more for "cosmetic" reasons, it doesn't really do anything

**Comment by Jalle19** [comment]
I meant I returned early so the method doesn't do any saving

**Comment by dborsatto** [comment]
As I said earlier, completely skipping the `save` part is not an option, because certain parts of the SDK rely on this, and in certain circumstances it may cause an infinite loop. Give me a second, I'm working on it! 😉

**Comment by Jalle19** [comment]
Okay, cool!

**Comment by dborsatto** [comment]
Hey @Jalle19 ,

would it be possible for you to test your application using the new branch I just pushed:
https://github.com/contentful/contentful.php/tree/feat/low-memory-resource-pool

You can enable the low-memory resource pool by calling `withLowMemoryResourcePool(true)` in the `ClientOptions` object. In my tests this vastly reduces the amount of used memory, though I wouldn't suggest using this on a regular application.

Let me know how this goes!

Cheers,

Davide

**Comment by Jalle19** [comment]
@dborsatto definitely better than before, although still not at 2.x levels:

```
$ php artisan contentful:assets:sync --ignoreExisting -vvv
Synchronizing assets/media...
 43075/43075 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100% 2 mins/2 mins 76.0 MiB

Done, synchronized 43075 assets
```

So currently it stays well below the 256 MB memory limit we have in place, but technically it still leakes memory so if possible a better solution would be preferred.

**Comment by Jalle19** [comment]
Yeah I understand that. Could you ping me once this feature is merged, then we can deploy this upgrade to our test environments and see if we find any other issues?

**Comment by dborsatto** [comment]
I want to do some more testing and polishing, so it's likely that I'll release 4.1.0 on Monday. I'll let you know as soon as it's out!

**Comment by dborsatto** [comment]
@Jalle19 I released version `4.1.0`, please with the PR changes, please take a look at it when you have some time 🙂

**Comment by Jalle19** [comment]
Nice, I'll report back once I've tested some more!

**Comment by Jalle19** [comment]
@dborsatto I tested synchronizing content instead of assets and there the memory leakage is still an issue (ignore the "not found" errors):

Before (SDK v2.x):

```
Synchronizing content of type "recipe"...
  3102/11179 [▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░]  27%  1 min/3 mins 60.0 MiB  Failed to synchronize maku_recipe_9234: The resource could not be found.
  3530/11179 [▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░]  31%  1 min/3 mins 60.0 MiB  Failed to synchronize maku_recipe_11697: The resource could not be found.
  6445/11179 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░]  57% 2 mins/3 mins 60.0 MiB  Failed to synchronize maku_recipe_11698: The resource could not be found.
  7925/11179 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░]  70% 2 mins/3 mins 60.0 MiB  Failed to synchronize maku_recipe_417: The resource could not be found.
  9296/11179 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░]  83% 3 mins/3 mins 60.0 MiB  Failed to synchronize maku_recipe_8105: The resource could not be found.
  9764/11179 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░]  87% 3 mins/3 mins 60.0 MiB  Failed to synchronize maku_recipe_1694: The resource could not be found.
 11179/11179 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100% 3 mins/3 mins 60.0 MiB

Done, synchronized 11173 entries
```

After (SDK v4.1.0):

```
Synchronizing content of type "recipe"...
  3192/11179 [▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░]  28%  1 min/6 mins 180.0 MiB  Failed to synchronize maku_recipe_9234: The resource could not be found.
  3522/11179 [▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░]  31% 2 mins/6 mins 186.0 MiB  Failed to synchronize maku_recipe_11697: The resource could not be found.
  5002/11179 [▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░]  44% 3 mins/7 mins 212.0 MiB
  5598/11179 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░]  50% 5 mins/11 mins 254.0 MiB

PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 2503920 bytes) in /vagrant/api/vendor/guzzlehttp/psr7/src/Stream.php on line 94
```

Any ideas on what we could do to prevent this? Can the client be "flushed" somehow so it forgets everything?

**Comment by dborsatto** [comment]
I tried loading about 40k entries and it didn't crash, reaching about 70MB of memory usage. Could you try profiling using blackfire and send me the link of the results?

**Comment by Jalle19** [comment]
@dborsatto our content is pretty big (sometimes we can't fetch 100 entries at once because we hit the 7.5 MB response size limit), maybe that's related?

I can try Blackfire at some point, although I've never used it so it may take a while.

**Comment by Jalle19** [comment]
@dborsatto I spoke too soon, I had forgotten to actually enable usage of the low resource memory pool... I'll post some new results shortly.

**Comment by Jalle19** [comment]
Got a little bit further:

```
Synchronizing content of type "recipe"...
  3198/11179 [▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░]  28% 36 secs/2 mins 50.0 MiB  Failed to synchronize maku_recipe_9234: The resource could not be found.
  3529/11179 [▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░]  31% 44 secs/2 mins 52.0 MiB  Failed to synchronize maku_recipe_11697: The resource could not be found.
  6444/11179 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░]  57% 6 mins/11 mins 152.0 MiB  Failed to synchronize maku_recipe_11698: The resource could not be found.
  7375/11179 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░]  65% 11 mins/16 mins 254.0 MiB

PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 716800 bytes) in /vagrant/api/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php on line 573
```

**Comment by Jalle19** [comment]
Unfortunately, when we're not ignoring existing items we still keep running out of memory.

**Comment by dborsatto** [comment]
Can I ask you what the synchronization does, exactly? I'm thinking that using the SDK might be a bit overkill, and you might be better off using the `contentful/core` utilities instead 🤔

**Comment by dborsatto** [comment]
For instance, if you're just dumping the serialized JSON on disk, we can perhaps think of a way of not building full-blown resources, but instead just keep a lightweight representation of them, which can be serialized later. WDYT?

**Comment by Jalle19** [comment]
Basically for each entry it builds a corresponding entity on "our side". Only scalar fields are resolved with the SDK - for links and link collections we use the ID and look up the corresponding entity from the database (i.e. we assume that all linked entries already exist on "our side").

This bulk synchronization code is shared with the parts that handle web hooks from Contentful.

I've been thinking about building some kind of custom SDK to handle our use cases better but it would take time, and since the 2.x SDK version has served us well enough so far we simply haven't gotten around to it.

**Comment by dborsatto** [comment]
A lot of basic functionality has been moved to `contentful/core` in the past few months (so it can also be used by the Management SDK), can I suggest you take a look at it and think what it would take for you to move to use that library? I can help fill the gaps of course.

I don't want to "give up" on this issue, but this use case is clearly a bit extreme for how the SDK was designed, so perhaps I can help you with coming up with a different and more appropriate solution 🙂

**Comment by Jalle19** [comment]
Sure, I'll try to find some time for this. If you come up with any other memory/performance tweaks in this library the meantime, feel free to ping me and I can test.
